### ISSUE TITLE
File listed for Manual Installation in ReadMe does not exist

### ISSUE THREAD

**Issue by lamachine** [FamousWolf/week-planner-card#106]
I tried using HACS (left comment under issue Add to hacs repository) but it says this repository is not valid.  I tried to follow manual download instructions and the file eweek-planner-card.js does not exists.  I also thought it may be a typo and searched for week-planner-card.js but that does not exist either.  

I did note that your Add to hacs repository issue was not closed yet, so if this is part of that same request, feel free to just close this one. 
 
Love your card, it does EXACTLY what I was looking for, so fingers crossed I can install it!

**Comment by lamachine** [comment]
I was wrong about the repository.  I had not installed HACS.  Took a while but got through it.  Update, when I tried to add the custom repository, it told me it was already in the store.  Downloaded and now hacking my way into it!

**Comment by FamousWolf** [comment]
There was indeed a typo in the manual. It should be `week-planner-card.js`. It has now been changed. If you go to https://github.com/FamousWolf/week-planner-card/releases/latest you can find and download it there, but as you've already installed in through HACS you won't need to download it from there.
