### ISSUE TITLE
Add legend for calendar colors

### ISSUE THREAD

**Issue by cstriffler** [FamousWolf/week-planner-card#107]
Add the ability to include a "legend" to indicate which color is which calendar.  Similar to attached image:
![image](https://github.com/user-attachments/assets/2c83dcc8-76b0-48eb-83e4-f6d1deb50c3f)

**Comment by Zwirbel1** [comment]
I second this, a legend would be nice for the colours.

Not related to this improvement:  @ cstriffler: how did you manage to colour the event text?

**Comment by cstriffler** [comment]
> I second this, a legend would be nice for the colours.
> 
> Not related to this improvement: @ cstriffler: how did you manage to colour the event text?

This is an example from another calendar just to illustrate the idea

**Comment by FamousWolf** [comment]
This has been added to the `dev` branch and will be included in the 1.7.0 release.

**Comment by FamousWolf** [comment]
You can enable the legend by adding `showLegend: true` to your configuration.

**Comment by FamousWolf** [comment]
There's a bug in the legend styling and the day columns. I've created a issue (#128) for it, will fix it soon and release a new version.

**Comment by Zwirbel1** [comment]
Thank you very much for this improvement.
