### ISSUE TITLE
Error while fetching calendar: Response error: 404

### ISSUE THREAD

**Issue by rbranham3** [FamousWolf/week-planner-card#110]
receiving 404 error using example config

**Comment by FamousWolf** [comment]
I can't reproduce this. Which example config did you try? Did you change anything (like the entity)?

**Comment by BirdCamp** [comment]
same problem here.
<img width="996" alt="Bildschirmfoto 2024-09-21 um 14 15 00" src="https://github.com/user-attachments/assets/0c224f8b-8ab4-4f23-a576-3faa326b6bf2">

**Comment by FamousWolf** [comment]
@BirdCamp Are your calendar entities actually named `my_calendar_1` and `my_calendar_2` or did you just copy/paste the example and not alter it?
