### ISSUE TITLE
Show past week

### ISSUE THREAD

**Issue by WueBumbum** [FamousWolf/week-planner-card#111]
Hello,

can I configure the calender to show also the events from last week?

best regards
Bumbum

**Comment by FamousWolf** [comment]
There's no way to do this right now. I can probably easily add a `startingDayOffset` option to make it possible. I'll see if I can add it to the next version.

**Comment by WueBumbum** [comment]
Thank you!

**Comment by FamousWolf** [comment]
This has been added to the `dev` branch and will be included in the 1.7.0 release.

**Comment by FamousWolf** [comment]
Setting the following configuration will show last week, this week and next week, starting with Monday:

```yaml
days: 21
startingDay: monday
startingDayOffset: -7
```

**Comment by WueBumbum** [comment]
Thank you, it is working!
