### ISSUE TITLE
Possible to filter text shown in a calendar entry

### ISSUE THREAD

**Issue by zapatos-design** [FamousWolf/week-planner-card#138]
I have several subscribed calendars that have superfluous text in the entry, for example a building and room number for a meeting that never changes. I've looked and tried several ways to filter repeating text (i.e. Building 4, Room 302) and only display pertinent information.  Any good ideas on how to accomplish this?

**Comment by FamousWolf** [comment]
This has been added to the dev branch and will be included in the 1.10.0 release.

**Comment by FamousWolf** [comment]
You can now filter the text using a regular expression globally or per calendar using the `filterText` option. For example:

```yaml
filterText: (Building|Room) [0-9]+
```

This will remove `Building` and `Room` followed by a space and one or more numbers from event texts.

**Comment by Adrianni** [comment]
Could this filter be expanded to change css (color, bold text, ie.) to the matched event, instead of just filtering to not be presented ?
