### ISSUE TITLE
Feature request: support for `FORECAST_TWICE_DAILY`

### ISSUE THREAD

**Issue by Wetzel402** [FamousWolf/week-planner-card#140]
Some [weather](https://developers.home-assistant.io/docs/core/entity/weather/#supported-features) integrations to not use `FORECAST_DAILY` but rather `FORECAST_TWICE_DAILY` and/or FORECAST_HOURLY.  In my case [NWS](https://www.home-assistant.io/integrations/nws/) does not support `FORECAST_DAILY`.

**Comment by FamousWolf** [comment]
This has been added to the dev branch and will be included in the 1.9.0 release.

Once released and updated, you can set it to use the twice daily forecast by setting the `weather.useTwiceDaily` option to `true`.
