### ISSUE TITLE
(Enhancement Request) Event Count

### ISSUE THREAD

**Issue by broyuken** [FamousWolf/week-planner-card#145]
It would be great if you could add an event count that could be listed underneath the date so I can see at a glance how many events there are that day.

**Comment by FamousWolf** [comment]
It's a bit too specific to add functionality for, but you can probably do it with CSS and card_mod. There is a counter in CSS. Something like this should work:

```yaml
card_mod:
  style: |
    div.day {
      counter-reset: events
    }
    div.day div.event {
      counter-increment: events
    }
    div.day div.events:after {
      content: counter(events);
    }
```

Displaying the counter does have to be after the events or the count will be zero, but you can use `position: absolute` to position it any way you like.
