### ISSUE TITLE
Filtering of duplicate events

### ISSUE THREAD

**Issue by JValmont** [FamousWolf/week-planner-card#148]
If one one family member creates an event and invites another family member, both events are displayed in the card.  If a family size is 6, then 6 duplicates will be displayed when all family members are invited.  Regex doesn't seem capable of  filtering all but on of these duplicates. 

Recommend a "Main Option" switch called "Combine Duplicates" (boolean) that will enable the card to perform an evaluation of events that occur at the same start and end times, check if title matches, and remove all but one.  (Primacy could go to first calendar listed in configuration).

Another solution (but more complicated) would be to combine events (in display) with matching start/end times and title, and display the colors of every calendar on which it appears.  This would provide "Skylight" levels of functionality.

**Comment by FamousWolf** [comment]
There's already another issue for this (#76)
