### ISSUE TITLE
Add compact mode styling

### ISSUE THREAD

**Issue by beyondwatts** [FamousWolf/week-planner-card#15]
Spacing on cards should be reduced for display on smaller screens

**Comment by beyondwatts** [comment]
I've created another PR for the additional tweaks #35

**Comment by FamousWolf** [comment]
Thanks. I've merged them to my branch. There are some conflicts I need to resolve, so I'll rebase it somewhere in the next few days, test it again and merge it. Then I'll release v1.2.0
