### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dennislittle** [FamousWolf/week-planner-card#159]
We have a calander for 4 persons. But our kids have 2 agenda`s (1 icloud and 1 ical for the footbalgames) i can add theme to the card but then there are 2 mentions in the legend for the same color. Is it possible to hide the calander from the legend? Siee attached. I can hide the legend but then it`s not clear who is who.

![image](https://github.com/user-attachments/assets/df705ab9-2cc6-455a-9187-76730e5740f4)

**Comment by FamousWolf** [comment]
I can add a `hideInLegend` configuration

**Comment by FamousWolf** [comment]
This has been added and will be included in the 1.8.0 release.
