### ISSUE TITLE
Issue installing via HACS, no "Lovelace" category either

### ISSUE THREAD

**Issue by genuser33** [FamousWolf/week-planner-card#163]
Hi, getting the following error when adding the custom repo:
<Integration FamousWolf/week-planner-card> Repository structure for v1.7.1 is not compliant

URL I'm using is https://github.com/FamousWolf/week-planner-card

There doesn't appear to be a "Category" anymore, instead it's "Type" now with only options available being Integration, Template, Dashboard and Theme

![HACS custom repo error](https://github.com/user-attachments/assets/0670d671-a922-4d39-8065-af93fe8b9db2)

I also tried the manual route, and while the js file shows up in Settings -> Dashboard -> Three Dots -> resources and is accessible, the card itself doesn't show up when adding.

Version info:
Core 2024.10.2
Supervisor 2024.10.2
Operating System 13.1
Frontend 20241002.3

**Comment by hfalk** [comment]
Same thing happened to me

**Comment by FamousWolf** [comment]
Yes, you should use `Dashboard`. This was changed in Hacs 2.0
