### ISSUE TITLE
Display issue of week-planner-card on iOS 15.8.3 (iPad Mini 4)

### ISSUE THREAD

**Issue by Elderas42** [FamousWolf/week-planner-card#166]
First of all, great card, by far the best looking calendar card for Home Assistant.

Unfortunately, on my wall mounted iPad Mini 4, the layout is kind of wrong. I attached two screenshots - one from my iPad Mini 4 and the other one from a modern iPad Pro (and other iOS and web browsers display it correctly). As the calendar would be one the key features of the wall-mount iPad, it would be great to know how I can fix it.

iPad Mini 4 (wrong)

![IMG_8FB7CB1E977D-1](https://github.com/user-attachments/assets/5128762c-be5f-4ec6-8fb5-7445b459c68c)

iPad Pro (right)

![IMG_0227](https://github.com/user-attachments/assets/e3b1df56-7951-4561-9979-7c3c020d6dcb)

Home Assistant 
Core 2024.10.2
Supervisor 2024.10.2
Operating System 13.2
Frontend 20241002.3

Week Planner Card v.1.7.1

**Comment by MicKress** [comment]
Same issue on my Android Tablet which is used as wall panel.

**Comment by FamousWolf** [comment]
It looks like the browser might be too old and not know the CSS I'm using. I think it's `@container` that's not working properly, so the default is used, which is 7 columns. If you can update the OS/Browser to a version that does support `@container` in CSS that should fix the problem. If not, you can probably fix it with card_mod. This should do it:

```yaml
card_mod:
  style: |
    .container .day {
      width: 100%;
    }
```

**Comment by jon-heller** [comment]
Hello, just wanted to say thank you as I had the same issue (using an old iPad as a tablet). However I did need to include the `!important` attribute:

```
card_mod:
  style: |
    .container .day {
      width: 100% !important;
    }
```
