### ISSUE TITLE
Feature Request: ability to set a firstDayOfMonth class on div that contains the date

### ISSUE THREAD

**Issue by hard2reid** [FamousWolf/week-planner-card#172]
I want to be able to add the name of the month to the first day of each month. 
Eg. 29, 30, Dec 1, 2, 3 etc...
I also want to be able to change the color of the text on a day where it is the first day of the month. 

One way to do this would be to add a css class (eg. firstDayOfMonth) to the div that displays the date when the date is the first day of a month.   

Then using: 
dayFormat: '''<span class="number">''d''</span> <span class="month">''MMMM''</span>'''

I would then set the visibility on the month class to hidden by default and then set the visibility on the month class to visible when the parent div has the firstDayOfMonth class. 
I would do something similar for changing the color of the text when the parent div has the firstDayOfMonth class. 

Example of code:
......
~~~
      <div class="date ${this._isFirstDayOfMonth(day.date) ? 'firstDayOfMonth' : ''}">
~~~
......

    _isFirstDayOfMonth(date) {
       return (date.day === 1);
    }

**Comment by hard2reid** [comment]
Actually this can be handled using the following with no coding changes:
card_mod:
      style: |
        .day[data-date="1"] {
           color: red !important
        }

**Comment by hard2reid** [comment]
Actually this can be handled using the following with no coding changes:
card_mod:
style: |
.day[data-date="1"] {
color: red !important
}

**Comment by Neocold** [comment]
I am trying to do the same thing you said in your first post
"I want to be able to add the name of the month to the first day of each month.
Eg. 29, 30, Dec 1, 2, 3 etc..."

I was able to change the color of the first day to red with the card_mod style your posted as your solution, but I can't seem to figure out how to add the day of the month to only the first day?

Thank You for your assistance!
