### ISSUE TITLE
Lovelace not in repository drop down list

### ISSUE THREAD

**Issue by HaViGit** [FamousWolf/week-planner-card#183]
I am trying to install the calendar according to your HACS instructions but the repository https://github.com/FamousWolf/week-planner-card cannot be added because the type Lovelace is not in the list (see image). This was previously reported by genuser33: https://github.com/FamousWolf/week-planner-card/issues/95#issuecomment-2412463052

Do you have a solution for this?

<img width="280" alt="HA" src="https://github.com/user-attachments/assets/f9f6aa7b-fec4-4b00-a30a-d0ea7a4a94ee">

**Comment by FamousWolf** [comment]
You should use Dashboard. This was changed in Hacs 2.0.

**Comment by HaViGit** [comment]
Thanks for helping and thanks for sharing this project!
