### ISSUE TITLE
Feature Request: Click on Legend to toggle calendar visibility

### ISSUE THREAD

**Issue by cstriffler** [FamousWolf/week-planner-card#186]
Still loving this!  One thing that could make it even better is that if you click on a calendar name in the legend, it would toggle visibility of that calendar (i.e. if all calendars are shown, but you click on one calendar name, that calendar's events would no longer be visibile - but it would still be in the legend.  If you click it again, the events would be visible again)

**Comment by FamousWolf** [comment]
This has been added to the dev branch and will be included in the 1.11.0 release.
