### ISSUE TITLE
Filter to include events that match filter criteria. 

### ISSUE THREAD

**Issue by mazi1987** [FamousWolf/week-planner-card#188]
It would be helpful to have the option to include only events that meet specific filter criteria (currently is the opposite) I subscribe to many public calendars but am typically interested in just a single type event from each.

**Comment by FamousWolf** [comment]
This is already possible, though you have to know regular expressions. Using `filter: ^((?!Foo|Bar).)*$` will filter out any events that don't contain `Foo` or `Bar`.
