### ISSUE TITLE
Global setting to fetch set amount of events.

### ISSUE THREAD

**Issue by mazi1987** [FamousWolf/week-planner-card#189]
Occasionally, when there are no events within the specified time frame, the card appears empty. On the other hand, if there are too many events, the card becomes oversized and disrupts the dashboard layout. It would be ideal to have a global setting across all calendars added to the card, limiting the display to a fixed number (e.g., 10) of upcoming events, regardless of how far in the future they occur.

**Comment by FamousWolf** [comment]
A maximum amount of events should be easy to implement. I'll probably implement this global and per day.

A minimum number of events is more difficult. Events are fetched per calendar and I have to specify a start and end date/time. I do not know beforehand how many events I'll get back. Even if I set the end date to 10 years in the future I might not get enough events. So to implement this I'd have to keep fetching more events for each calendar until I have enough to satisfy this minimum. This could create infinite loops if there are no more events in the future. I would have to implement a hard stop at some point.

I think the minimum number is too niche a usecase to implement something this complicated. Once the maximum amount of events is implemented you could set the end date to some future date that would always yield enough events for your case and use the maximum events setting to show the fixed number you want.

**Comment by mazi1987** [comment]
You’re right; setting a maximum number of events makes more sense. But why would you implement it on a per-day basis?

**Comment by FamousWolf** [comment]
I know some people show a small calendar with multiple columns for the next couple of days and if you click on it you go to the full calendar. Having a maximum per day (with a +n message if there are more) will make that fit better between other cards.

**Comment by mazi1987** [comment]
That makes sense. Looking forward for this implementation!! Many thanks.

**Comment by FamousWolf** [comment]
I've added a `maxEvents` and `maxDayEvents` option. This change has been added to the dev branch and will be included in the 1.11.0 release.
