### ISSUE TITLE
Horizontal (panel) view on sections layout

### ISSUE THREAD

**Issue by adminotaurus44** [FamousWolf/week-planner-card#190]
It would be nice to have the horizontal view from a panel dashboard inside a section with the size of all sections possible.

Maybe it is possible already but I don't know how.

![grafik](https://github.com/user-attachments/assets/99830935-cbb2-4638-96ec-73d90a1c8f36)

**Comment by FamousWolf** [comment]
I am planning to redo the whole columns layout, because I want to make it more configurable. But I'm not sure if it's going to be possible to do it in this way and it might be a while before I get around to it.

Until then, you could do 3 different week-planner cards with a single day and use `startingDayOffset` to show different days for each.

**Comment by adminotaurus44** [comment]
Thank you very much for your quick reply. I'm looking forward to any future improvements because I like your card and I was really surprised there is nothing like that out there. Keep up the good work! 

> Until then, you could do 3 different week-planner cards with a single day and use startingDayOffset to show different days for each.

I like the idea and I'll try to figure something out but I want to show a whole week or maybe 10 days in horizontal row.

**Comment by FamousWolf** [comment]
> I like the idea and I'll try to figure something out but I want to show a whole week or maybe 10 days in horizontal row.
I don't think I understood you correctly. I thought you meant you wanted to show 3 days, each the width of 1 section.

The number of columns is based on the size of the card. In the next release (1.11.0) there will be an easy way to override this though. You can already override it using some custom CSS with card-mod:

```yaml
card_mod:
  style: |
    .day {
      width: calc((100% - 6 * var(--days-spacing)) / 7) !important;
    }
```

This will set the number of columns to 7, no matter the width of the card. The first number `6` is the number of gaps between the columns (or the number of columns minus 1) and the second number `7` is the number of columns. This will however make it not responsive, so it will always be a fixed number of columns, even on your mobile for example.
