### ISSUE TITLE
Feature Request: Option to use description instead of title

### ISSUE THREAD

**Issue by dhanjel** [FamousWolf/week-planner-card#202]
This might not be that common, but the school here has the food for the week in a publicly available calendar. Problem is that they for some reason have one of the two alternatives each day as the title and then the complete menu as the description.

It would be nice to have a Boolean-flag on each calendar entry stating if it should display the description instead.

Example entry (Google translate from Swedish):

Title:
> Kale soup is served with boiled egg, bread, cheese and fruit and salad buffet

Description
> Lunch 1: Kale soup served with boiled egg, bread, cheese and fruit and salad buffet
> Lunch 2: Minestrone soup served with bread, cheese and fruit and salad buffet

**Comment by FamousWolf** [comment]
I'm going to add a `showTitle` (default true) and a `showDescription` (default false) option, just like there's already a `showLocation` option. That way people can set it to show either or both (or none, though I don't see why you'd want that).

**Comment by FamousWolf** [comment]
I've also added a `eventTitleField` option to override the field used as title. This has to be set per calendar.

The changes have been added to the dev branch and will be included in the 1.11.0 release.

**Comment by dhanjel** [comment]
@FamousWolf Nice! Would it be possible to add it to the calendar object as well to specify it for individual calendars?
