### ISSUE TITLE
Change background and font color

### ISSUE THREAD

**Issue by HaViGit** [FamousWolf/week-planner-card#213]
Excuse me for bothering you with a beginner's question. I would like to change the background color (now white) and the font color (now black). Can you tell me where / which file and how to do that? Thanks in advance!

<img width="782" alt="Calendar" src="https://github.com/user-attachments/assets/c609d224-23b6-4a3c-adc1-82e3d2f0edc9">

**Comment by FamousWolf** [comment]
You can remove the card background using the `noCardBackground` option (under "Appearance" in the visual editor). You can also change the background color of the events using the `eventBackground` option (also under "Appearance").

If you want to change the colors you'd either need a [custom theme](https://www.home-assistant.io/integrations/frontend/) or [card-mod](https://github.com/thomasloven/lovelace-card-mod).

You can also try activating dark mode in your user profile.

**Comment by HaViGit** [comment]
Thnaks again for helping!

**Comment by Hexadecimalism** [comment]
> You can remove the card background using the `noCardBackground` option (under "Appearance" in the visual editor). You can also change the background color of the events using the `eventBackground` option (also under "Appearance").
> 
> If you want to change the colors you'd either need a [custom theme](https://www.home-assistant.io/integrations/frontend/) or [card-mod](https://github.com/thomasloven/lovelace-card-mod).
> 
> You can also try activating dark mode in your user profile.



Can the ``eventBackground`` be removed or made transparent like ``noCardBackground``?
