### ISSUE TITLE
Recommended HACS installation not working

### ISSUE THREAD

**Issue by HaViGit** [FamousWolf/week-planner-card#214]
When I install according to your recommended instructions with HACS according to their instructions on https://hacs.xyz/docs/faq/custom_repositories/ everything seems to go well (see image) and then I restart HA (latest version on RPi 5) to be sure. 

When I then want to add your planner to a card it is nowhere to be found, not in entities, not in cards or anywhere else. Besides the following code was also not added to configuration.yaml:

```
resources:
  - url: /local/week-planner-card.js?version=1.11.0
type: module
```
Is that code not needed? Am I doing something wrong?

<img width="259" alt="HACS-Finished" src="https://github.com/user-attachments/assets/e9aa9406-908c-4daa-b32c-c5a3739cd95d">

**Comment by FamousWolf** [comment]
I've just tested it and it works for me. After adding the custom repository, you do still have to install the card itself in HACS. If you have done that and it's still not working, try clearing the browser cache.

**Comment by HaViGit** [comment]
You're right, the browser cache caused the problem. Thanks for helping and for sharing this week planner.
