### ISSUE TITLE
Daytime Grid / Schedule

### ISSUE THREAD

**Issue by mirisbowring** [FamousWolf/week-planner-card#217]
Currently, the meetings are just stacked on each other per day and take up the space that is necessary to show them.

for better visual understanding, when and how long a meeting takes, it would be great (as an option) to have a daytime grid like in common calendars.

Heartdisplay is doing it e.g.:
![image](https://github.com/user-attachments/assets/4a598766-e27d-4419-bff2-22011198b002)

or the skylight calendar max:
![image](https://github.com/user-attachments/assets/c341d3e1-d0f3-4ece-8d63-3e1ed5c38933)

**Comment by FamousWolf** [comment]
There are no plans to add a view like this. It's too big a change for the current code base. This card was created as a simple overview, not a full calendar. But it is a possible feature for version 2.0 (which I'm not planning yet, so it might be a while). There's also already an issue for this (https://github.com/FamousWolf/week-planner-card/issues/165), so I'm closing this one.
