### ISSUE TITLE
Request: Hide "Private" events

### ISSUE THREAD

**Issue by comm** [FamousWolf/week-planner-card#223]
If an event is marked as "Private" on the calendar, can we have an option to either be shown as "Busy" or not show the event?

**Comment by comm** [comment]
> @comm How would an event be marked as "Private" on a calendar?

In .ics files from Google Calendar they are marked with:
`CLASS:PRIVATE`

**Comment by FamousWolf** [comment]
@comm I've just tested it and I'm not getting that from the HA calendar API. So this will have to be added to that (and the Google Calendar or ICS Integration) first before I can do anything with it.
