### ISSUE TITLE
locale option doesn't translate "Today" and "Tomorrow"

### ISSUE THREAD

**Issue by Jahislove** [FamousWolf/week-planner-card#228]
Hello
locale option doesn't translate  "Today" and "Tomorrow" , other week days are OK
i try to use option today:""  and tomorrow: "Demain" but without success
![image](https://github.com/user-attachments/assets/008f78ad-2478-4915-9200-b591b50d52b2)

![image](https://github.com/user-attachments/assets/412f5569-6e3e-4f75-8d7f-12fbc8d4561e)

**Comment by FamousWolf** [comment]
The locale only translates the day/month names, not "Today" or "Tomorrow" (or "Yesterday"). The translations for those are under "Texts". I can't say for sure from the screenshot of your yaml, but I think you didn't put those under `texts`. It should be like this:

```yaml
texts:
  today: ""
  tomorrow: "Demain"
```

**Comment by FamousWolf** [comment]
If it still doesn't work, let me know and I'll reopen this issue.

**Comment by Jahislove** [comment]
thx , it's work better with texts:
