### ISSUE TITLE
adjust days for weather

### ISSUE THREAD

**Issue by rikvanzoest** [FamousWolf/week-planner-card#23]
Can we adjust how many days weather is shown? currently have it showing two rows of 5, so 10 days. Weather is shown for 6 of them, which means the weather is shown only on the first day of the second row. It's a tiny detail, but if it's an easy adjustment that would be great.

**Comment by FamousWolf** [comment]
I also noticed this and I think this is a limit in the weather entity or the API. I'm not limiting the forecast on my side as far as I know. But I will look into it to see if there's anything that can be done on the card side.

**Comment by FamousWolf** [comment]
Yes, it looks like this is a limitation in the weather entity or the API behind it. I'm showing weather for all the days I'm getting for the entity. Unfortunately it looks like there's nothing I can do about this.
