### ISSUE TITLE
Ability to set Start Day for the week view

### ISSUE THREAD

**Issue by f00lycooly** [FamousWolf/week-planner-card#24]
Hi, just wondering if its posible to set a specific start day for the view, so that it shows for example Sunday to Saturday as a fixed week instead of refreshing to Today being the first day?

**Comment by FamousWolf** [comment]
Not right now, but it is something I'm considering adding if it doesn't add too much complexity.

**Comment by f00lycooly** [comment]
Legend, thank you!

I was almost at the point of trying to write one of these myself, so immensly glad you've released this!

**Comment by Nolux** [comment]
Great work on this feature! Thank you!
