### ISSUE TITLE
Make columns configurable

### ISSUE THREAD

**Issue by FamousWolf** [FamousWolf/week-planner-card#41]
Right now the number of columns is hardcoded based on the width of the card. This should be made configurable. It should still be responsive, but the cutoff points and the number of columns should be configurable.

**Comment by FamousWolf** [comment]
It looks like CSS variables can not be used in container queries and LitElement doesn't have a way to make the CSS dynamic. I'll have to research this some more. I'm going to remove the milestone for now.

**Comment by wobeco** [comment]
sehr schöne Arbeit ... DANKE!
Wird es ggf. möglich sein, die Orientierung der aufeinanderfolgenden Tage (hier: 14) von horizontal 
Mo - Di
Mi - Do
Fr - Sa
So - Mo 
...

auf vertikal 
Mo   Mo
Di     Di
Mi    Mi
Do   Do
Fr    Fr
Sa   Sa
So   So

konfigurieren zu können?
Danke für eine Berücksichtigung

**Comment by FamousWolf** [comment]
@wobeco My German is nearly non-existent, but if I understand you correctly your question is not related to this issue. Can you please create a new issue for your question in English?

**Comment by FamousWolf** [comment]
@wobeco As far as I can see there's no easy way to do this. You could use a card for each day, using `startingDay` and `startingDayOffset` to give them each a different day, and align them in the new sections view. But without knowing how many events there are for each they it's going to be hard to align I think.

**Comment by FamousWolf** [comment]
Configurable columns has been added to the dev branch and will be included in the 1.11.0 release.
