### ISSUE TITLE
Style past events differently

### ISSUE THREAD

**Issue by FamousWolf** [FamousWolf/week-planner-card#52]
It is possible to hide past events with `hidePastEvents` in configuration, but it should also be possible to still show the past events and style them differently.

**Comment by Jab2870** [comment]
Not sure how much control you are planning on putting in the card itself, but one solution to this might be simply adding a class to events (and days) of things like "past", "future", "ongoing" which would make styling with card_mod possible

**Comment by FamousWolf** [comment]
From version 1.5.0 (next release) this can be done using card_mod. See [documentation](https://github.com/FamousWolf/week-planner-card?tab=readme-ov-file#custom-styling-using-cardmod)
