### ISSUE TITLE
Hide days without any events

### ISSUE THREAD

**Issue by beringtom** [FamousWolf/week-planner-card#53]
Would like to suggest an option to hide days without anything planned.

- Today should always be shown even without events.
-  "days" options should still be respected to still only show events x days in the future.

**Comment by FamousWolf** [comment]
Can you check if https://github.com/FamousWolf/week-planner-card/pull/54 does what you had in mind?

**Comment by beringtom** [comment]
Yep description and logic looks like it should display events within the next X days if there are any and always display "today" even if empty.

cool, can't wait to try it out.

**Comment by labaland** [comment]
@FamousWolf , How to i hide days without events? i dont know how to see #54 xD noob here on github
