### ISSUE TITLE
Ability to show month

### ISSUE THREAD

**Issue by Jab2870** [FamousWolf/week-planner-card#55]
First off, thanks for creating this. It looks amazing. 

I am using it to show a lot more than a week though. It would be useful if there was some way to differentiate months. I think the most simple would be to add the option to have the month visible? Perhaps something like this

![image](https://github.com/FamousWolf/week-planner-card/assets/1909202/639dd571-2d4a-4a03-9c31-24ddbcd5213d)

**Comment by FamousWolf** [comment]
@Jab2870 So you only want it shown for the first of the month?

**Comment by Jab2870** [comment]
That wasn't my intention. I was trying to show where it could be rather than how. I think it would be preferable if it was NOT just on the first of the month.

**Comment by FamousWolf** [comment]
What I could do is make the format of the date optionally configurable. That way you can add the month there and style it with card_mod (if needed). You could then set it to something like `'<span class="number">'d'</span> <span class="month">'MMMM'</span>'`, which would result in for example `<span class="number">19</span> <span class="month">May</span>`.

**Comment by FamousWolf** [comment]
This has been changed in the `dev` branch and will be part of the upcoming 1.6.0 release.
