### ISSUE TITLE
Highlight today's date

### ISSUE THREAD

**Issue by ocean75** [FamousWolf/week-planner-card#60]
Good day,
This is an awesome project, thank you! It would be beneficial if there were a way to make today's date BOLD, or CIRCLED, or possibly place a LINE underneath the date, or in any way different from the rest of the dates for easier overview.

**Comment by mcrcclifford** [comment]
The below code assumes that that the startingDay fixed as Monday.
now().weekday() will return 0 for Monday, 1 for Tuesday, etc. 
nth-of-type will apply only to the nth date shown.
                card_mod:
                      style: |
                        ha-card {
                          margin-top: 25px;
                        }
                        div.container>div:nth-of-type({{ now().weekday()+1 }}) {
                           background-color: rgba(122,37,37,1.0);
                          border-radius: 12px;
                        }

**Comment by FamousWolf** [comment]
From version 1.5.0 (next release) this can be done using card_mod. See [documentation](https://github.com/FamousWolf/week-planner-card?tab=readme-ov-file#custom-styling-using-cardmod)

For example, this will make the date number/text red for today:

```yaml
card_mod:
  style: |
    .day.today .date {
      color: red;
    }
```
