### ISSUE TITLE
Have calendar start on first day of month

### ISSUE THREAD

**Issue by Hillaryandseth** [FamousWolf/week-planner-card#65]
I'd like the calendar to start on the first day of the month and show the whole month. Essentially like the included calendar card but yours is much more customizable.

**Comment by FamousWolf** [comment]
I've added 2 new settings:

- A new value `month` for `days` configuration, setting the value to the number of days in the current month
- A new value `month` for `startingDay` configuration, setting the start date to the first day of the current month

This will be included in the next release (1.5.0), which will be released soon.
