### ISSUE TITLE
Show only "tomorrow", "the day after tomorrow" etc.

### ISSUE THREAD

**Issue by hAMMERlized** [FamousWolf/week-planner-card#69]
Hello,

thanks for this great card. I am playing around with it and i am wondering if it's possible to show only the tomorrow date or the day after tomorrow? Maybe with card-mod?

So basically i would like to set "days: 2" but hiding the current day.

Thanks

**Comment by FamousWolf** [comment]
@hAMMERlized You can set `startingDay` to `tomorrow` and `days` to `1`. This will only show tomorrow. There is no option to start with the day after tomorrow though;.
