### ISSUE TITLE
Custom Colors Per Calendar

### ISSUE THREAD

**Issue by broyuken** [FamousWolf/week-planner-card#71]
I have a few different calendars for each family member I have the full background color set via card mod, not just the bar. As such, some calendars I need to have darker text vs others, otherwise it's hard to read white text on a light background. I'm requesting the ability to set text color for the events, times, etc per calendar, not just overall. Can this already be done via card_mod?

**Comment by FamousWolf** [comment]
@broyuken I could add a `data-entity` attribute to each event's outer div with the entity identifier in it. That way you can style it using something like `div.event[data-entity="calendar.mycalendar"]`. Would that work for you?

**Comment by broyuken** [comment]
That sounds like it may work.

**Comment by broyuken** [comment]
Would that allow me to change the color of the title and the other text in an individual calendar? For example any of the family calendar entries should have black title text and grey body text, but my calendar should have white text.

**Comment by FamousWolf** [comment]
Yes, it should

**Comment by FamousWolf** [comment]
This has been added to the `dev` branch and will be included in the 1.6.0 release.

**Comment by broyuken** [comment]
Thank you, I just updated and this seems to work for the title, but not the time. 

This works
```
card_mod:
  style: |
    .day.future .date {
      color: grey;
    }
    .event.past {
      opacity: .3;
    }
    .event {
      background-color: var(--border-color) !important;
    }
    .container .day .events .event[data-entity="calendar.isabela"] {
      color: green;
    }
```

But how would I target just the time? I tried adding .time after .event but that didn't seem to work.

**Comment by broyuken** [comment]
Nevermind, figured it out. You just put .time AFTER the calendar name

```
card_mod:
  style: |
    .day .date {
      color: var(--state-icon-active-color);
    }
    .day.future .date {
      color: var(--primary-text-color);
    }
    .event.past {
      opacity: .3;
    }
    .event {
      background-color: var(--border-color) !important;
    }
    .container .day .events .event[data-entity="calendar.isabela"] .time {
      color: green;
    }
```

**Comment by zapatos-design** [comment]
This works great, but one question - how would you style remaining calendars? What am I missing?
Also, is it possible to add a percentage of the var(--border-color)? I like having the color, but too strong for my theme.
Thanks!
