### ISSUE TITLE
Full Day Event not showing when starting day is today

### ISSUE THREAD

**Issue by Psykosoldier** [FamousWolf/week-planner-card#72]
The Full Day Events are not showing for me when starting day is today.

As a workaround I have to set the starting day to yesterday, then they show in the today section.

- Component Version v1.4.0
- Home Assistant OS 12.3
- Home Assistant Core Version 2024.6.1

**Comment by FamousWolf** [comment]
I'm unable to reproduce this issue, but it could be a timezone problem. Is this also a problem for you with other calendar cards?

**Comment by Psykosoldier** [comment]
I don’t have this problem with other calendar cards.

The other card I use regularly is „Atomic Calendar Revive“.


Mit freundlichen Grüßen

Dennis Ennenbach


Rudy Gnodde ***@***.***> schrieb am Do. 27. Juni 2024 um
15:43:

**Comment by FamousWolf** [comment]
I think this could be the same problem as #77. What timezone are you in?

**Comment by FamousWolf** [comment]
@Psykosoldier It looks like it is the same problem as #77. That has now been fixed and version 1.5.1 has been released. Can you test if this fixes your problem. If not, please reopen this issue.

**Comment by Psykosoldier** [comment]
> @Psykosoldier It looks like it is the same problem as #77. That has now been fixed and version 1.5.1 has been released. Can you test if this fixes your problem. If not, please reopen this issue.

Thanks for your work regarding this issue. It fixed the problem for me!

Good job @FamousWolf! #
