### ISSUE TITLE
Entire Month not working

### ISSUE THREAD

**Issue by SupiTrobi** [FamousWolf/week-planner-card#73]
When I try to show the entire month nothing will be displayed.

Component Version v1.4.0
Home Assistant OS 12.3
Home Assistant Core Version 2024.6.1

**Comment by FamousWolf** [comment]
This was added in version 1.5.0, which I've just released. If you update, it should work.

**Comment by SupiTrobi** [comment]
Works like a charm. Thy alot for that. Your card is very useful. THX.
