### ISSUE TITLE
Primacy of Calendars

### ISSUE THREAD

**Issue by maranhaoBruno** [FamousWolf/week-planner-card#74]
How is the primacy of calendars determined when it comes time to display events with the same starting time, e.g. entire day events? It doesn't appear to be related to the sequence in which the calendars are entered in the card yaml.

**Comment by FamousWolf** [comment]
I think it's just whichever calendar delivers its data first. I'll have to look into it to see if that's true and if I can easily add some sort of sorting.

**Comment by FamousWolf** [comment]
This has been added to the `dev` branch and will be included in the 1.7.0 release. Events are first sorted by start time. If the start time of multiple events are the same, they will be sorted by the ordered the calendars are listed in the configuration.
