### ISSUE TITLE
Release version 1.5

### ISSUE THREAD

**Issue by dennisvandehoef** [FamousWolf/week-planner-card#75]
Heey,

What is the planned release date for version 1.5.0? 
_(HACS does not offer an update)_

I see some features that I would like to use for my styling 😸

**Comment by broyuken** [comment]
Curious about this as well, this may solve some of the issues I'm seeing.

**Comment by broyuken** [comment]
@FamousWolf could you please push this version out to hacs?

**Comment by FamousWolf** [comment]
Due to health issues I was out of the running for a while, but I'm back now. Sorry about that. I've just released version 1.5.0.

**Comment by broyuken** [comment]
Health is more important than a home assistant plugin. Feel better and thanks for the work you’re doing here!
