### ISSUE TITLE
Request: Combine events

### ISSUE THREAD

**Issue by doctorkb** [FamousWolf/week-planner-card#76]
As a user with multiple calendars for each family member, I'd like to have events that match (presumably by title and times) to be collapsed into one entry with the calendar colours stacked so that I can reduce clutter.

E.g. this could be one entry with blue, pink, and purple lines on the left side:
![image](https://github.com/FamousWolf/week-planner-card/assets/1383663/1a000b07-2b4e-46ef-b74d-6713c38bbf9a)

**Comment by FamousWolf** [comment]
I tried to do this when I first created the card, but unfortunately it's not easy. But I'll give it another go soon.

**Comment by cstriffler** [comment]
I'm not sure technically how to do this, but could you nest multiple event <div> tags inside each other - one for each calendar with the right colors for the left border so in this example, there would be 3 nested and 3 border colors?

**Comment by FamousWolf** [comment]
This has been added to the dev branch and will be included in the 1.9.0 release.
