### ISSUE TITLE
Issue Installing via HACS

### ISSUE THREAD

**Issue by SimeonSouttar** [FamousWolf/week-planner-card#95]
Getting the following error when adding the custom repo:
<Integration FamousWolf/week-planner-card> Repository structure for v1.5.1 is not compliant

**Comment by FamousWolf** [comment]
What URL are you using for the repository?

**Comment by Diizzee** [comment]
I'm seeing the same issue.

The URL I'm adding is:
https://github.com/FamousWolf/week-planner-card

**Comment by FamousWolf** [comment]
@Diizzee @SimeonSouttar The category should be `Lovelace`, not `Integration`. Can you check if it works if you use the correct category?

**Comment by Diizzee** [comment]
Perfect that worked. I tried template and integration, I didn't think to try lovelace, thank you.

**Comment by fairytaletrash** [comment]
Any chance you can update the README to include the category of lovelace?  I had to search through the issues to find this information.

**Comment by genuser33** [comment]
> @Diizzee @SimeonSouttar The category should be `Lovelace`, not `Integration`. Can you check if it works if you use the correct category?

Hi, came across this closed issue trying to install this card. Apologies if I shouldn't be responding to this and opening a new issue instead. Am new to HA and HACS (day2). When trying to add this week planner through HACS custom repo I get the same error, but unfortunately "Lovelace" isn't an option for "Type". The only options visible are Integration, Template, Dashboard and Theme. What can I do to fix?
