### ISSUE TITLE
Request: Add CSS class for weekend (or days of the week)

### ISSUE THREAD

**Issue by alistair-marshall** [FamousWolf/week-planner-card#96]
I am currently using the rolling week format, which is nice, but it can be hard to spot the weekend. It would be nice to format the weekend days differently (probably a different background color).

Please could you add a CCS class to describe the day or whether it is the weekend.

Thanks,

**Comment by FamousWolf** [comment]
This has been changed in the `dev` branch and will be part of the upcoming 1.6.0 release.
