### ISSUE TITLE
Request: add a title to the card

### ISSUE THREAD

**Issue by alistair-marshall** [FamousWolf/week-planner-card#97]
Please add a configurable 'title' to the card.

I am using my calendar different than most, I have actually used the calendar 5 times, once for 'whole family' events, then a different card for each member of the family. Each card may have multiple ical calendars within it, but it is only relating to that person.

This is reimplementing the whiteboard we have beside the dinner table, but hopefully with less manual updates required!

![image](https://github.com/FamousWolf/week-planner-card/assets/3950932/effbf55d-d01d-4ae1-b5b9-1f029978df5f)

It would be nice if each person's name appeared at the top of their card. A configurable title (similar to many other cards) would be great.

Thanks,

**Comment by alistair-marshall** [comment]
Update: I have managed a workaround by changing the 'today' string to the name of person, then added a non-breaking space for every other day's string.
I will keep this open, as a proper title would still be nice, but I am happy enough with the workaround.

**Comment by FamousWolf** [comment]
This has been changed in the `dev` branch and will be part of the upcoming 1.6.0 release.
